name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read      # Necessário para o checkout do código
  issues: write       # Permite criar comentários em issues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Inicializar Terraform
        run: terraform init
        working-directory: terraform/s3-bucket-static

      - name: Validar Terraform
        run: terraform validate
        working-directory: terraform/s3-bucket-static

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: terraform/s3-bucket-static

      - name: Comentar na issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: "✅ Deploy do Terraform finalizado com sucesso!"
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
